services:
  api-dev:
    container_name: threat-api-dev
    restart: unless-stopped
    build:
      target: dev
      context: .
    ports:
      - "3000:3000"
      - "9229:9229"
    volumes:
      - ./src:/app/src
    env_file:
      - .env
    environment:
      - NODE_ENV=development
    command: pnpm run start:dev